### ISSUE TITLE
some way go back from Enter new symbol to Add/remove new symbol page

### ISSUE THREAD

**Issue by shenevol** [kaddopur/twse#13]
Step to reproduce:
1. choose **Symbols**
2. change to **Add/remove you symbols** page, choose **Add new**
3. change to **Enter new symbol** page

Actual Result:
There is no way back to previous **Add/remove Symbols** page in **Enter new symbol** page.
If user does not want to add any symbol at this time, then the only way to exit is to close this problem to restart.

Expect Result:
Add some ways (e.g. enter **exit** string) to go back to **Add/remove Symbols** page

**Comment by kaddopur** [comment]
fixed with [v1.3.1](https://github.com/kaddopur/twse/releases/tag/v1.3.1)
